// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Entry struct {
	EntryID   uuid.UUID    `json:"entry_id"`
	UserID    int64        `json:"user_id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	Title     string       `json:"title"`
	Body      string       `json:"body"`
}

type User struct {
	UserID       int64        `json:"user_id"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
	FirstName    string       `json:"first_name"`
	LastName     string       `json:"last_name"`
	Username     string       `json:"username"`
	Hash         string       `json:"hash"`
	Email        string       `json:"email"`
	Token        string       `json:"token"`
	TokenExpires time.Time    `json:"token_expires"`
}
